version: '3.8'

services:
  fix-now-api:
    build: .
    container_name: fix-now-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379"
