version: '3.8'

services:
  fix-now-api:
    build: .
    container_name: fix-now-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:fixnowdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-ui
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=test

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=test
    command: [ "redis-server", "--requirepass", "test" ]
