server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:fixnowdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-ui

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      password: test
      timeout: 60000 # 60 secs

security:
  jwt:
    secret-key: U2VkZWJlZ2VuZXJhcnVuYXNlbWlsbGFsb3N1ZmljaWVudGVtZW50ZWdyYW5kZXBhcmFwb2RlcnF1ZWN1bXBsYWNvbmxvc3JlcXVpc2l0b3M=
    expiration-in-minutes: 30

logging:
  level:
    org:
      springframework:
        security: DEBUG
